### ISSUE TITLE
KAU_EMBEDED_19_GIT 사용법

### ISSUE THREAD

**Issue by KimYC1223** [KimYC1223/KAU_EMBEDED_19#2]
# 1 . 개요

---

#1 이슈를 보면, 친절하게 설명이 잘 되어 있지만

실제로 따라하기엔 시간을 상당히 오래 잡아먹기 때문에

수업시간 데모 검사 시간 안에 구현하기엔 무리가 있다.

그래서 일단 필요한 파일만 깃 허브에 올리기로 한다.

다음은 우리의 항공대 19년도 1학기 임베디드 시스템 설계 및 실습 GIT의 사용법이다.

누군가가  새로운 sof파일과 sopcinfo파일을 만들었다고 한다면,

아래와 같이 진행하도록 하자.

---

# 2 . git pull

일단 누군가가 새로운 sof파일과 sopcinfo를 만들었다는 것은, 누군가가 Qsys를 이용하여 하드웨어 아키텍쳐를 수정했다는 뜻이며,

이는 누군가가 30분 이상을 잡아먹는 쿼터스를 성공적으로 컴파일 해서 다른 팀원에게 공유를 하고 싶다는 뜻이다.

일단, 새로 만들어진 sof파일과 sopcinfo파일을 받아오기 위해, 우리의 깃 저장 디렉토리 ( 나의 경우엔 C:\src\KAU_EMBEDED_19 ) 으로 이동한 다음, 빈 공간에 마우스 오른쪽 클릭을 한다.

![image](https://user-images.githubusercontent.com/40852277/57198085-ba769300-6fa9-11e9-83b8-932422a5f7f8.png)

Git Bash Here 클릭.

![image](https://user-images.githubusercontent.com/40852277/57198096-ceba9000-6fa9-11e9-88f7-e29ef81c9798.png)

다른 사람이 올린 깃에 올린 파일을 받기 위해서 git pull 명령어를 사용한다.

조금 기다리면 다운로드가 완료 될 것이다.

다운로드가 완료된 후, 확인해 보면 Quartus 폴더가 생길 것인데, 들어가보면 아래와 같다.

![image](https://user-images.githubusercontent.com/40852277/57198109-fa3d7a80-6fa9-11e9-95a3-62763b86aeaf.png)

각 폴더별로 기능은 다음과 같다.

| 이름 | 기능 |
|:---:|:---:|
|SOF_FILE|SOF 파일들을 모아 놓은 장소|
|SOPCINFO_FILE|sopcinfo 파일을 모아 놓은 장소|
|software|이클립스에서 불러올 장소|

아직 이해가 잘 안갈 수 있다. 하지만 다음 예를 보면서 차근 차근 따라하자.

만약, 누군가 VGA를 8Bit Grayscale로 출력하는 시스템을 새로 만들었고, 그 이름을 VGA_GRAY라고 지었다고 하자.

이 경우, 다른 사용자들이 이 VGA_GRAY.sof와 VGA_GRAY.sopcinfo를 사용하는 방법은 아래와 같다.

---

# 3 . Quartus

일단, Quartus를 실행시키고, Programmer를 실행시킨다. **( 프로젝트를 열 필요도 없다. )**

![image](https://user-images.githubusercontent.com/40852277/57198196-0b3abb80-6fab-11e9-99f1-5a2bda6228ea.png)

오토 디텍트를 한다.

![image](https://user-images.githubusercontent.com/40852277/57198198-155cba00-6fab-11e9-85e9-c1c1b813d5e6.png)

두번째 선택 후 OK

![image](https://user-images.githubusercontent.com/40852277/57198203-286f8a00-6fab-11e9-81c2-926cf71af619.png)

두 번째 "none" 클릭 후, Change File을 누른다.

![image](https://user-images.githubusercontent.com/40852277/57198216-450bc200-6fab-11e9-8313-403d6d5729dd.png)

그러면 sof파일을 선택하는 창이 뜨는데, 깃폴더\Quartus\SOF_FILE\파일이름.sof 을 선택한다. 여기서는 VGA_GRAY이므로,

C:\src\KAU_EMBEDED_19\Quartus\SOF_FILE 에 있는 VGA_GRAY.sof파일일 것이다.

고르고 Open 클릭.

![image](https://user-images.githubusercontent.com/40852277/57198251-8b612100-6fab-11e9-9788-204d1f830902.png)

그러면 이런 창이 뜨는데 그냥 무시하고 OK누른다.

![image](https://user-images.githubusercontent.com/40852277/57198252-961bb600-6fab-11e9-91e7-0a428412c868.png)

바뀐 모습을 볼 수 있다.

![image](https://user-images.githubusercontent.com/40852277/57198254-a16ee180-6fab-11e9-8559-a6bf259b38da.png)

두 번째에서 Program/Configure 체크 후 스타트.

![image](https://user-images.githubusercontent.com/40852277/57198257-b2b7ee00-6fab-11e9-8391-a96d93df9fbf.png)

이런 창이 뜨는데 무시하고 Cancel 누른다.

---

# 4 . Eclipes

여기서 부터는 최초 1회면 하면 되는 과정이다.

즉, 누군가가 VGA_GRAY를 만들어서 올렸다고 한다면, 딱 한번만 이 과정을 진행 하도록 하고, 다음 부터는 하지 않아도 된다.

물론, VGA_GRAY가 만들어진 이후에 누군가가 새로운 하드웨어 아키텍쳐인 ~~~를 컴파일 하여 ~~~.sof와 ~~~.sopcinfo를 만들었다면, 새로 만들어진 ~~~에 대해서도 다음의 최초 1회의 과정을 해줘야 한다.

일단, 이클립스를 켜고, Project Explorer의 빈 공간에서 마우스 우클릭 후, Import를 클릭한다.

![image](https://user-images.githubusercontent.com/40852277/57198338-80f35700-6fac-11e9-9f28-52d6984fcc86.png)

그럼 이런 창이 뜰텐데, General 을 클릭한다.

![image](https://user-images.githubusercontent.com/40852277/57198345-92d4fa00-6fac-11e9-97ae-3cd9f2f124b4.png)

그럼 Existing Projects into Workspace 를 누르고 Next

![image](https://user-images.githubusercontent.com/40852277/57198356-ad0ed800-6fac-11e9-9c53-b8cc04eea3dc.png)

이런 창이 뜬다면, Select root directory를 선택하고 Browse

![image](https://user-images.githubusercontent.com/40852277/57198366-d596d200-6fac-11e9-85a3-dfd65121d722.png)

깃주소\Quartus\software\아키텍쳐이름 의 폴더를 선택한다. 여기서는 C:\src\KAU_EMBEDED_19\Quartus\software\VGA_GRAY\ 가 되겠다.

그 후, Finish를 하면,

![image](https://user-images.githubusercontent.com/40852277/57198400-31615b00-6fad-11e9-8ff5-12712f02c567.png)

이렇게 폴더가 생긴 것을 볼 수 있다.

같은 방법으로 아키텍쳐이름_bsp 이름의 폴더도 Import해 준다. 여기서는 C:\src\KAU_EMBEDED_19\Quartus\software\VGA_GRAY_bsp\가 되겠다.

![image](https://user-images.githubusercontent.com/40852277/57198414-69689e00-6fad-11e9-9c2e-b11ba8758594.png)

그럼 이렇게 정상적으로 프로젝트가 로딩 된 모습을 볼 수 있다.

이 이후엔 일반적인 프로젝트처럼 Run > Nios II Hardware로 실행시키면 된다.

---

**Comment by KimYC1223** [comment]
우리 깃의 [WIKI 페이지](https://github.com/KimYC1223/KAU_EMBEDED_19/wiki/HOW-TO-USE-%22KAU_EMBEDED_19_GIT%22-%3F)에도 등록 해 놓았습니다.

이 이슈는 언제나 쉽게 볼 수 있도록 나중에 클로즈 하도록 하겠습니다

**Comment by KimYC1223** [comment]
현재 해당 기능이 잘 동작하지 않습니다.

일단 원인을 파악중이니 조금만 기다려주세요

**Comment by rudcks2020** [comment]
확인하였습니다.
